### ISSUE TITLE
not removing birthdays

### ISSUE THREAD

**Issue by braindigitalis** [scottbucher/BirthdayBot#148]
The bot is assigning the birthday role to various people and then never removing it. 

We haven't changed the role or its settings in over a year. We have someone right now who had the birthday role since 16th july.

Without a discord to approach for support i found this github via top.gg which is the only place i can log the issue. Can you please investigate?

**Comment by scottbucher** [comment]
The command `bday support` links you to our discord as well as the top.gg website, the readme on the github, the command `bday help` and various other places.

The bot was having issues (bugs & crashing) for a little over a week around the time you are describing as it was going through an update. This is why birthday roles weren't properly removed (the bot wasn't online to remove them).

**Comment by scottbucher** [comment]
I will assume this issue has been resolved.

**Comment by RiZ266** [comment]
Hi there I also have an issue with the birthday not not removing birthday roles after 24hrs. It's been 2 days and a user still hasn't had the role removed by the bot. Is there a command for the bot we can use to remove the role ourselves instead if having the server owner do it?

**Comment by scottbucher** [comment]
The bot should be automatically removing the birthday role after 24 hours assuming all permissions are correct. 

Please check that the birthday bot's highest role is :
1) above the birthday role
2) above the celebrant's highest role

Assuming this is correct, and the bot has the MANAGE_ROLES permission, the bot should remove the birthday role 24 hours after the celebrant's birthday.

If all of these are correct and it still didn't remove the role, the bot may have missed it for one of the following reasons:

1) Discord/Discord API was down or having issues (https://status.discord.com)
2) The celebrant change their birthday between the time it was given and the time it was supposed to be removed
3) The bot was offline for maintenance

In any of the above cases, you will have to manually remove the birthday role as the bot currently only checks once, 24 hours after the celebrant's birthday, to remove it.
