### ISSUE TITLE
Incorrect handling of Feb 29th

### ISSUE THREAD

**Issue by greebowarrior** [scottbucher/BirthdayBot#192]
Alerts should be sent on Feb 28th, not March 1st in non-leap years

**Comment by RafaCintron** [comment]
People born on february 29 were born the day AFTER february 28, which corresponds to march 1 on non leap years.

**Comment by greebowarrior** [comment]
Trust me when I say I have a very deep insight into this matter, the majority of us celebrate on Feb 28th, as "last day of February" is always an accurate statement

**Comment by greebowarrior** [comment]
Can confirm this is now working as expected
