### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ZanderBrown** [scottbucher/BirthdayBot#204]
Your project appears to be a derivative of [Discord-Bot-TypeScript-Template](https://github.com/KevinNovak/Discord-Bot-TypeScript-Template), whilst MIT is ‘non-infectious’ you are required to maintain the notice

Further, you declare your ‘No License’ intentions in the README —  yet your packages [are MIT'ed](https://github.com/scottbucher/BirthdayBot/blob/81d547284259be49076710125bb744219da02727/package.json#L6), ironically this is probably an oversight having been retained from the aforementioned package

Finally, I would ask that you reconsider your ‘No License’ decision, perhaps a restrictive licence such as AGPL would achieve your goals?

IANAL

**Comment by scottbucher** [comment]
> Your project appears to be a derivative of [Discord-Bot-TypeScript-Template](https://github.com/KevinNovak/Discord-Bot-TypeScript-Template), whilst MIT is ‘non-infectious’ you are required to maintain the notice
While I probably should have it listed Kevin and I developed the template together.

> Further, you declare your ‘No License’ intentions in the README — yet your packages [are MIT'ed](https://github.com/scottbucher/BirthdayBot/blob/81d547284259be49076710125bb744219da02727/package.json#L6), ironically this is probably an oversight having been retained from the aforementioned package
It is probably leftover from the template that Kevin and I developed together as I mentioned, I can update it.
