### ISSUE TITLE
Purge birthdays for users who have left the server.

### ISSUE THREAD

**Issue by mywynne** [scottbucher/BirthdayBot#223]
We're a fair sized server and have had lots of members leave over time. The bot still drops happy birthday message for ex-members - is there any way to prevent that or clean it up so only current server members are birthday'd?

<img width="416" alt="Screenshot 2024-01-30 at 9 02 52 AM" src="https://github.com/scottbucher/BirthdayBot/assets/11491154/b7c79272-2bac-41ed-8312-b2f2c450abd2">

**Comment by scottbucher** [comment]
Hi, these users have not left the server, at least, they hadn't left the server when their birthday was announced. Fix this using the name format setting outlined here: https://birthdaybot.scottbucher.dev/faq-1/general#what-is-the-name-format-setting

For more support open a forum post in our support server: https://discord.gg/39w2cnBRa2
